name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["type: feature"]
body:
- type: markdown
  attributes:
    value: |
      **Quick guide**: Describe what you want and why it's useful.
      Skip optional fields for simple ideas.

- type: textarea
  id: description
  attributes:
    label: What feature or improvement?
    description: Describe what should be added or changed
  validations:
    required: true

- type: textarea
  id: use-case
  attributes:
    label: Use case
    description: What problem does this solve? What would you use it for?
    placeholder: "When modeling X, I need to do Y..."

- type: textarea
  id: api-idea
  attributes:
    label: API idea (optional)
    description: How might it work? Sketch a rough API if you have ideas
    placeholder: |
      # Example:
      component = fx.NewThing(
          label='example',
          param=value
      )
    render: python
