# This workflow will install Python dependencies and run tests and lint with multiple versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: flixOpt Test on Push

on:
  push:
    tags:
      - v*  # Triggers on version tags like v1.0.0
    release:
      types: [ created, published ]  # Runs when a release is created or published
    branches:
      - feature/ci-cd
      - main
      - next/*
  pull_request:
    branches:
      - feature/ci-cd
      - main
      - next/*

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']  # Using strings, as 3.10. is mistaken to be 3.1 (bug)

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run tests
      run: pytest -v -p no:warnings
